// <auto-generated />
using System;
using Consolidado.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Consolidado.Api.Data.Migrations
{
    [DbContext(typeof(ConsolidadoDbContext))]
    [Migration("20261005231321_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Consolidado.Api.Data.EventoProcessado", b =>
                {
                    b.Property<Guid>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("evento_id");

                    b.Property<DateTimeOffset>("ProcessadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processado_em");

                    b.HasKey("EventoId")
                        .HasName("pk_eventos_processados");

                    b.ToTable("eventos_processados", (string)null);
                });

            modelBuilder.Entity("Consolidado.Api.Domain.SaldoDiario", b =>
                {
                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<decimal>("TotalCreditos")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("total_creditos");

                    b.Property<decimal>("TotalDebitos")
                        .HasPrecision(20, 2)
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("total_debitos");

                    b.HasKey("Data")
                        .HasName("pk_saldo_diario");

                    b.ToTable("saldo_diario", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
